/var/log/bsb-reporting/pgbouncer.log {
    weekly
    maxsize 8M
    rotate 4
    compress
    delaycompress
    missingok
    notifempty
    create 0640 postgres postgres
    postrotate
        /bin/systemctl kill --kill-who=main --signal=HUP pgbouncer.service >/dev/null 2>&1 || true
    endscript
}
