# SPDX-License-Identifier: AGPL-3.0-or-later
"""
Django settings for SBtools project.

Generated by 'django-admin startproject' using Django 3.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

ALLOWED_HOSTS = ['*']

INSTALLED_APPS = [
    'analytics_store.apps.AnalyticsStoreConfig',
    'browser.apps.BrowserConfig',
    'django_tables2',
    'django_filters',
    'django_bootstrap5',
    'django.contrib.contenttypes',
    'django.contrib.staticfiles',
]

DATABASE_ROUTERS = ['analytics_store.router.AnalyticsDatabaseRouter']

MIDDLEWARE = [
    'django.middleware.cache.UpdateCacheMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.cache.FetchFromCacheMiddleware',
]

ROOT_URLCONF = 'SBtools.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'browser/../../browser/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
            ],
        },
    },
]

WSGI_APPLICATION = 'SBtools.wsgi.application'

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

STATIC_URL = '/static/'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
}

CACHE_MIDDLEWARE_SECONDS = 30

# Statistics API compatibility settings. Database statistics always come from
# the reporting database configured in the active settings module.
STATS_MAX_REWARD_TIME_PER_SEGMENT_SECONDS = int(
    os.environ.get('STATS_MAX_REWARD_TIME_PER_SEGMENT_SECONDS', '86400')
)
STATS_HTTP_TIMEOUT_SECONDS = float(os.environ.get('STATS_HTTP_TIMEOUT_SECONDS', '5'))
STATS_USER_COUNTER_URL = os.environ.get('STATS_USER_COUNTER_URL', '')
STATS_DATA_FILE = os.environ.get(
    'STATS_DATA_FILE',
    os.path.join(os.path.dirname(BASE_DIR), 'data', 'statistics.json'),
)
